export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const UN_AUTHENTICATE_USER = 'UN_AUTHENTICATE_USER';
